// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Noog_api.Data;

#nullable disable

namespace Noog_api.Migrations
{
    [DbContext(typeof(NoogDbContext))]
    partial class NoogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Noog_api.Models.Summary", b =>
                {
                    b.Property<int>("SummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SummaryId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SummaryId");

                    b.ToTable("Summaries");

                    b.HasData(
                        new
                        {
                            SummaryId = 1,
                            Content = "This is the content of the first summary.",
                            CreatedAt = new DateTime(2025, 10, 1, 9, 20, 41, 789, DateTimeKind.Utc).AddTicks(7013),
                            Title = "First Summary"
                        },
                        new
                        {
                            SummaryId = 2,
                            Content = "This is the content of the second summary.",
                            CreatedAt = new DateTime(2025, 10, 1, 9, 20, 41, 789, DateTimeKind.Utc).AddTicks(7014),
                            Title = "Second Summary"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
