using Noog_api.Models.AssemblyAi;

namespace Noog_api.Models.Application
{
    public class GroupMeeting : BaseEntity
    {
        public Guid Id { get; set; }

        // CallId is generated by streamIO - could be a GUID too.
        public string CallId { get; set; } 
        public ICollection<Transcript> Transcripts { get; set; } = new List<Transcript>();

        public Guid ProjectGroupId { get; set; }
        public ProjectGroup ProjectGroup { get; set; }
    }
}
