name : Backend CI/CD

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'Backend-api/**'
      - 'Tests/BackendApi.Tests/**'
  push:
    branches: [main]
    paths:
      -  'Backend-api/**'

jobs:
  test:
    if: github.event_name == 'pull_request'
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore Backend-api/Noog-api/Noog-api.sln
      - name: Build
        run: dotnet build Backend-api/Noog-api/Noog-api.sln --no-restore --configuration Release
      - name: Run Tests
        run: dotnet test Tests/BackendApi.Tests/BackendApi.Tests.csproj --no-build --configuration Release --logger "console;verbosity=detailed"

  deploy:
    if: github.event_name == 'push'
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore Backend-api/Noog-api/Noog-api.sln
      - name: Publish Backend
        run: dotnet publish Backend-api/Noog-api/Noog-api.sln -c Release -o ${{github.workspace}}/publish

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy to Azure
        run: az webapp deploy --resource-group NoogResourceGroup --name NoogApi --src-path ${{github.workspace}}/publish --type zip
          
